name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y cmake libpng-dev libqrencode-dev pkg-config

      - name: Create build directory
        run: mkdir -p build

      - name: Configure with CMake
        run: cmake -S . -B build
  
      - name: Build project
        run: cmake --build build
